/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.shipping.engine.fixed.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AccountEntryShippingOptionRel service. Represents a row in the &quot;AccountEntryShippingOptionRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.shipping.engine.fixed.model.impl.AccountEntryShippingOptionRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.shipping.engine.fixed.model.impl.AccountEntryShippingOptionRelImpl</code>.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see AccountEntryShippingOptionRel
 * @generated
 */
@ProviderType
public interface AccountEntryShippingOptionRelModel
	extends AuditedModel, BaseModel<AccountEntryShippingOptionRel>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account entry shipping option rel model instance should use the {@link AccountEntryShippingOptionRel} interface instead.
	 */

	/**
	 * Returns the primary key of this account entry shipping option rel.
	 *
	 * @return the primary key of this account entry shipping option rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account entry shipping option rel.
	 *
	 * @param primaryKey the primary key of this account entry shipping option rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this account entry shipping option rel.
	 *
	 * @return the mvcc version of this account entry shipping option rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this account entry shipping option rel.
	 *
	 * @param mvccVersion the mvcc version of this account entry shipping option rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the account entry shipping option rel ID of this account entry shipping option rel.
	 *
	 * @return the account entry shipping option rel ID of this account entry shipping option rel
	 */
	public long getAccountEntryShippingOptionRelId();

	/**
	 * Sets the account entry shipping option rel ID of this account entry shipping option rel.
	 *
	 * @param accountEntryShippingOptionRelId the account entry shipping option rel ID of this account entry shipping option rel
	 */
	public void setAccountEntryShippingOptionRelId(
		long accountEntryShippingOptionRelId);

	/**
	 * Returns the company ID of this account entry shipping option rel.
	 *
	 * @return the company ID of this account entry shipping option rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account entry shipping option rel.
	 *
	 * @param companyId the company ID of this account entry shipping option rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account entry shipping option rel.
	 *
	 * @return the user ID of this account entry shipping option rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this account entry shipping option rel.
	 *
	 * @param userId the user ID of this account entry shipping option rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account entry shipping option rel.
	 *
	 * @return the user uuid of this account entry shipping option rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this account entry shipping option rel.
	 *
	 * @param userUuid the user uuid of this account entry shipping option rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this account entry shipping option rel.
	 *
	 * @return the user name of this account entry shipping option rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this account entry shipping option rel.
	 *
	 * @param userName the user name of this account entry shipping option rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this account entry shipping option rel.
	 *
	 * @return the create date of this account entry shipping option rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account entry shipping option rel.
	 *
	 * @param createDate the create date of this account entry shipping option rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account entry shipping option rel.
	 *
	 * @return the modified date of this account entry shipping option rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account entry shipping option rel.
	 *
	 * @param modifiedDate the modified date of this account entry shipping option rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account entry ID of this account entry shipping option rel.
	 *
	 * @return the account entry ID of this account entry shipping option rel
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this account entry shipping option rel.
	 *
	 * @param accountEntryId the account entry ID of this account entry shipping option rel
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the channel ID of this account entry shipping option rel.
	 *
	 * @return the channel ID of this account entry shipping option rel
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this account entry shipping option rel.
	 *
	 * @param channelId the channel ID of this account entry shipping option rel
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the shipping method key of this account entry shipping option rel.
	 *
	 * @return the shipping method key of this account entry shipping option rel
	 */
	@AutoEscape
	public String getShippingMethodKey();

	/**
	 * Sets the shipping method key of this account entry shipping option rel.
	 *
	 * @param shippingMethodKey the shipping method key of this account entry shipping option rel
	 */
	public void setShippingMethodKey(String shippingMethodKey);

	/**
	 * Returns the shipping option key of this account entry shipping option rel.
	 *
	 * @return the shipping option key of this account entry shipping option rel
	 */
	@AutoEscape
	public String getShippingOptionKey();

	/**
	 * Sets the shipping option key of this account entry shipping option rel.
	 *
	 * @param shippingOptionKey the shipping option key of this account entry shipping option rel
	 */
	public void setShippingOptionKey(String shippingOptionKey);

	@Override
	public AccountEntryShippingOptionRel cloneWithOriginalValues();

}