##
## Test Suites
##

    modified.files.includes[relevant][commerce-product-search-web-portlet-instance-configuration-name-playwright-rule]=**

    relevant.rule.names=\
        commerce-product-search-web-portlet-instance-configuration-name-playwright-rule

    test.batch.names[relevant][commerce-product-search-web-portlet-instance-configuration-name-playwright-rule]=\
        playwright-js-tomcat90-mysql57

    #
    # Relevant
    #

    playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][commerce-product-search-web-portlet-instance-configuration-name-playwright-rule]=\
        commerce-product-search-web-portlet-instance-configuration-name.main