components:
    schemas:
        Error:
            properties:
                errorCode:
                    description:
                        Internal error code mapping
                    example: 996
                    readOnly: true
                    type: integer
                errorDescription:
                    example: Unable to find currency. Currency code should be expressed with
                        3-letter ISO 4217 format.
                    readOnly: true
                    type: string
                message:
                    example: No CommerceCurrency exists with the key {groupId=41811, code=US
                        Dollar}
                    readOnly: true
                    type: string
                status:
                    description:
                        HTTP Status code
                    example: 404
                    readOnly: true
                    type: integer
            required:
                - errorCode
                - errorDescription
                - message
                - status
            type: object
        Payment:
            properties:
                amount:
                    example: 101
                    format: bigdecimal
                    type: number
                comment:
                    example: Account Name
                    type: string
                id:
                    example: 30130
                    format: int64
                    minimum: 0
                    type: integer
                reason:
                    example: Product Defect
                    type: string
                relatedItemId:
                    example: 30130
                    format: int64
                    minimum: 0
                    type: integer
                type:
                    example: Refund
                    type: string
    securitySchemes:
        BasicAuth:
            scheme: basic
            type: http
        BearerAuth:
            scheme: bearer
            type: http
        OAuth2:
            flows:
                authorizationCode:
                    authorizationUrl: /oauth/authorize
                    scopes:
                        CommerceOpenApiAdmin.admin: Grants access to admin operations
                        CommerceOpenApiAdmin.read: Grants read access
                        CommerceOpenApiAdmin.write: Grants write access
                    tokenUrl: /oauth/token
            type: oauth2
info:
    contact:
        email: team-commerce@liferay.com
        name: Commerce Team
    description:
        "Liferay Commerce Admin Payment API. A Java client JAR is available for use with the group ID 'com.liferay',
        artifact ID 'com.liferay.headless.commerce.admin.payment.client', and version '4.0.34'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: Liferay Commerce Admin Payment API
    version: v1.0
openapi: 3.0.0
paths:
    /payments:
        get:
            operationId: getPaymentsPage
            parameters:
                - in: query
                  name: filter
                  required: false
                  schema:
                      type: string
                - in: query
                  name: page
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  required: false
                  schema:
                      type: integer
                - in: query
                  name: search
                  required: false
                  schema:
                      type: string
                - in: query
                  name: sort
                  required: false
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Payment"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Payment"
                                type: array
                    description:
                        Successful operation
                400:
                    description:
                        Invalid input
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            security:
                - BasicAuth: []
                - BearerAuth: []
                - OAuth2:
                      - CommerceOpenApiAdmin.read
            summary: Gets a List of Payments.
            tags:
                - Payment
        post:
            operationId: postPayment
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Payment"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Payment"
                required: true
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Payment"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Payment"
                    description:
                        Created
                202:
                    description:
                        Accepted - Async
                204:
                    description:
                        Updated
                400:
                    description:
                        Invalid input
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            security:
                - BasicAuth: []
                - BearerAuth: []
                - OAuth2:
                      - CommerceOpenApiAdmin.write
            summary: Creates or updates a Payment.
            tags:
                - Payment
    /payments/{id}:
        delete:
            operationId: deletePayment
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      description:
                          The resource Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
            responses:
                204:
                    description:
                        No content
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
            security:
                - BasicAuth: []
                - BearerAuth: []
                - OAuth2:
                      - CommerceOpenApiAdmin.write
            summary: Deletes an Payment by ID.
            tags:
                - Payment
        get:
            operationId: getPayment
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      description:
                          The resource Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Payment"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Payment"
                    description:
                        Successful operation
                400:
                    description:
                        Invalid input
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            security:
                - BasicAuth: []
                - BearerAuth: []
                - OAuth2:
                      - CommerceOpenApiAdmin.read
            summary: Gets an Payment by ID.
            tags:
                - Payment
        patch:
            operationId: patchPayment
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      description:
                          The resource Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Payment"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Payment"
                required: true
            responses:
                202:
                    description:
                        Async
                204:
                    description:
                        Updated
                400:
                    description:
                        Invalid input
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            security:
                - BasicAuth: []
                - BearerAuth: []
                - OAuth2:
                      - CommerceOpenApiAdmin.write
            summary: Updates an Payment by ID.
            tags:
                - Payment
servers:
    - description:
          Liferay Commerce API server
      url: https://commerce.{environment}.liferay.com/commerce-admin-payment/{basePath}
      variables:
          basePath:
              default: v1.0
          environment:
              default: api
              enum:
                  - api
                  - api.dev
                  - api.uat
    - description:
          Liferay Commerce Local Development (Hosts file)
      url: "{protocol}://{host}:{port}/o/commerce-admin-payment/{basePath}"
      variables:
          basePath:
              default: v1.0
          host:
              default: test.dev
          port:
              default: "8080"
              enum:
                  - "443"
                  - "8080"
                  - "8443"
          protocol:
              default: http
              enum:
                  - http
                  - https
    - description:
          Liferay Commerce Local Development with Ngrok
      url: "{protocol}://{host}.ngrok.io/o/commerce-admin-payment/{basePath}"
      variables:
          basePath:
              default: v1.0
          host:
              default: commerce
          protocol:
              default: http
              enum:
                  - http
                  - https
    - description:
          SwaggerHub API Auto Mocking
      url:
          https://virtserver.swaggerhub.com/liferayinc/commerce-admin-payment/v1.0