/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.shipping.engine.fixed.model.impl;

import com.liferay.commerce.shipping.engine.fixed.model.AccountEntryShippingOptionRel;
import com.liferay.commerce.shipping.engine.fixed.model.AccountEntryShippingOptionRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AccountEntryShippingOptionRel service. Represents a row in the &quot;AccountEntryShippingOptionRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AccountEntryShippingOptionRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountEntryShippingOptionRelImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see AccountEntryShippingOptionRelImpl
 * @generated
 */
@JSON(strict = true)
public class AccountEntryShippingOptionRelModelImpl
	extends BaseModelImpl<AccountEntryShippingOptionRel>
	implements AccountEntryShippingOptionRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account entry shipping option rel model instance should use the <code>AccountEntryShippingOptionRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "AccountEntryShippingOptionRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"AccountEntryCSOptionRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"accountEntryId", Types.BIGINT},
		{"channelId", Types.BIGINT}, {"shippingMethodKey", Types.VARCHAR},
		{"shippingOptionKey", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("AccountEntryCSOptionRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("shippingMethodKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("shippingOptionKey", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AccountEntryShippingOptionRel (mvccVersion LONG default 0 not null,AccountEntryCSOptionRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountEntryId LONG,channelId LONG,shippingMethodKey VARCHAR(75) null,shippingOptionKey VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table AccountEntryShippingOptionRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY accountEntryShippingOptionRel.accountEntryShippingOptionRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AccountEntryShippingOptionRel.AccountEntryCSOptionRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SHIPPINGOPTIONKEY_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCOUNTENTRYSHIPPINGOPTIONRELID_COLUMN_BITMASK =
		16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.shipping.engine.fixed.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.commerce.shipping.engine.fixed.model.AccountEntryShippingOptionRel"));

	public AccountEntryShippingOptionRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _accountEntryShippingOptionRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAccountEntryShippingOptionRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _accountEntryShippingOptionRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AccountEntryShippingOptionRel.class;
	}

	@Override
	public String getModelClassName() {
		return AccountEntryShippingOptionRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AccountEntryShippingOptionRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AccountEntryShippingOptionRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEntryShippingOptionRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(AccountEntryShippingOptionRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AccountEntryShippingOptionRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AccountEntryShippingOptionRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AccountEntryShippingOptionRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AccountEntryShippingOptionRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AccountEntryShippingOptionRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AccountEntryShippingOptionRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AccountEntryShippingOptionRel.class.getClassLoader(),
			AccountEntryShippingOptionRel.class, ModelWrapper.class);

		try {
			Constructor<AccountEntryShippingOptionRel> constructor =
				(Constructor<AccountEntryShippingOptionRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<AccountEntryShippingOptionRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<AccountEntryShippingOptionRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<AccountEntryShippingOptionRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AccountEntryShippingOptionRel, Object>>();
		Map<String, BiConsumer<AccountEntryShippingOptionRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<AccountEntryShippingOptionRel, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", AccountEntryShippingOptionRel::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::setMvccVersion);
		attributeGetterFunctions.put(
			"accountEntryShippingOptionRelId",
			AccountEntryShippingOptionRel::getAccountEntryShippingOptionRelId);
		attributeSetterBiConsumers.put(
			"accountEntryShippingOptionRelId",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::
					setAccountEntryShippingOptionRelId);
		attributeGetterFunctions.put(
			"companyId", AccountEntryShippingOptionRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::setCompanyId);
		attributeGetterFunctions.put(
			"userId", AccountEntryShippingOptionRel::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::setUserId);
		attributeGetterFunctions.put(
			"userName", AccountEntryShippingOptionRel::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AccountEntryShippingOptionRel, String>)
				AccountEntryShippingOptionRel::setUserName);
		attributeGetterFunctions.put(
			"createDate", AccountEntryShippingOptionRel::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AccountEntryShippingOptionRel, Date>)
				AccountEntryShippingOptionRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AccountEntryShippingOptionRel::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AccountEntryShippingOptionRel, Date>)
				AccountEntryShippingOptionRel::setModifiedDate);
		attributeGetterFunctions.put(
			"accountEntryId", AccountEntryShippingOptionRel::getAccountEntryId);
		attributeSetterBiConsumers.put(
			"accountEntryId",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::setAccountEntryId);
		attributeGetterFunctions.put(
			"channelId", AccountEntryShippingOptionRel::getChannelId);
		attributeSetterBiConsumers.put(
			"channelId",
			(BiConsumer<AccountEntryShippingOptionRel, Long>)
				AccountEntryShippingOptionRel::setChannelId);
		attributeGetterFunctions.put(
			"shippingMethodKey",
			AccountEntryShippingOptionRel::getShippingMethodKey);
		attributeSetterBiConsumers.put(
			"shippingMethodKey",
			(BiConsumer<AccountEntryShippingOptionRel, String>)
				AccountEntryShippingOptionRel::setShippingMethodKey);
		attributeGetterFunctions.put(
			"shippingOptionKey",
			AccountEntryShippingOptionRel::getShippingOptionKey);
		attributeSetterBiConsumers.put(
			"shippingOptionKey",
			(BiConsumer<AccountEntryShippingOptionRel, String>)
				AccountEntryShippingOptionRel::setShippingOptionKey);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getAccountEntryShippingOptionRelId() {
		return _accountEntryShippingOptionRelId;
	}

	@Override
	public void setAccountEntryShippingOptionRelId(
		long accountEntryShippingOptionRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountEntryShippingOptionRelId = accountEntryShippingOptionRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountEntryId = accountEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAccountEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("accountEntryId"));
	}

	@JSON
	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	@JSON
	@Override
	public String getShippingMethodKey() {
		if (_shippingMethodKey == null) {
			return "";
		}
		else {
			return _shippingMethodKey;
		}
	}

	@Override
	public void setShippingMethodKey(String shippingMethodKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_shippingMethodKey = shippingMethodKey;
	}

	@JSON
	@Override
	public String getShippingOptionKey() {
		if (_shippingOptionKey == null) {
			return "";
		}
		else {
			return _shippingOptionKey;
		}
	}

	@Override
	public void setShippingOptionKey(String shippingOptionKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_shippingOptionKey = shippingOptionKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalShippingOptionKey() {
		return getColumnOriginalValue("shippingOptionKey");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AccountEntryShippingOptionRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AccountEntryShippingOptionRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AccountEntryShippingOptionRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AccountEntryShippingOptionRelImpl accountEntryShippingOptionRelImpl =
			new AccountEntryShippingOptionRelImpl();

		accountEntryShippingOptionRelImpl.setMvccVersion(getMvccVersion());
		accountEntryShippingOptionRelImpl.setAccountEntryShippingOptionRelId(
			getAccountEntryShippingOptionRelId());
		accountEntryShippingOptionRelImpl.setCompanyId(getCompanyId());
		accountEntryShippingOptionRelImpl.setUserId(getUserId());
		accountEntryShippingOptionRelImpl.setUserName(getUserName());
		accountEntryShippingOptionRelImpl.setCreateDate(getCreateDate());
		accountEntryShippingOptionRelImpl.setModifiedDate(getModifiedDate());
		accountEntryShippingOptionRelImpl.setAccountEntryId(
			getAccountEntryId());
		accountEntryShippingOptionRelImpl.setChannelId(getChannelId());
		accountEntryShippingOptionRelImpl.setShippingMethodKey(
			getShippingMethodKey());
		accountEntryShippingOptionRelImpl.setShippingOptionKey(
			getShippingOptionKey());

		accountEntryShippingOptionRelImpl.resetOriginalValues();

		return accountEntryShippingOptionRelImpl;
	}

	@Override
	public AccountEntryShippingOptionRel cloneWithOriginalValues() {
		AccountEntryShippingOptionRelImpl accountEntryShippingOptionRelImpl =
			new AccountEntryShippingOptionRelImpl();

		accountEntryShippingOptionRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		accountEntryShippingOptionRelImpl.setAccountEntryShippingOptionRelId(
			this.<Long>getColumnOriginalValue("AccountEntryCSOptionRelId"));
		accountEntryShippingOptionRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		accountEntryShippingOptionRelImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		accountEntryShippingOptionRelImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		accountEntryShippingOptionRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		accountEntryShippingOptionRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		accountEntryShippingOptionRelImpl.setAccountEntryId(
			this.<Long>getColumnOriginalValue("accountEntryId"));
		accountEntryShippingOptionRelImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));
		accountEntryShippingOptionRelImpl.setShippingMethodKey(
			this.<String>getColumnOriginalValue("shippingMethodKey"));
		accountEntryShippingOptionRelImpl.setShippingOptionKey(
			this.<String>getColumnOriginalValue("shippingOptionKey"));

		return accountEntryShippingOptionRelImpl;
	}

	@Override
	public int compareTo(
		AccountEntryShippingOptionRel accountEntryShippingOptionRel) {

		long primaryKey = accountEntryShippingOptionRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AccountEntryShippingOptionRel)) {
			return false;
		}

		AccountEntryShippingOptionRel accountEntryShippingOptionRel =
			(AccountEntryShippingOptionRel)object;

		long primaryKey = accountEntryShippingOptionRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AccountEntryShippingOptionRel> toCacheModel() {
		AccountEntryShippingOptionRelCacheModel
			accountEntryShippingOptionRelCacheModel =
				new AccountEntryShippingOptionRelCacheModel();

		accountEntryShippingOptionRelCacheModel.mvccVersion = getMvccVersion();

		accountEntryShippingOptionRelCacheModel.
			accountEntryShippingOptionRelId =
				getAccountEntryShippingOptionRelId();

		accountEntryShippingOptionRelCacheModel.companyId = getCompanyId();

		accountEntryShippingOptionRelCacheModel.userId = getUserId();

		accountEntryShippingOptionRelCacheModel.userName = getUserName();

		String userName = accountEntryShippingOptionRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			accountEntryShippingOptionRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			accountEntryShippingOptionRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			accountEntryShippingOptionRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			accountEntryShippingOptionRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			accountEntryShippingOptionRelCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		accountEntryShippingOptionRelCacheModel.accountEntryId =
			getAccountEntryId();

		accountEntryShippingOptionRelCacheModel.channelId = getChannelId();

		accountEntryShippingOptionRelCacheModel.shippingMethodKey =
			getShippingMethodKey();

		String shippingMethodKey =
			accountEntryShippingOptionRelCacheModel.shippingMethodKey;

		if ((shippingMethodKey != null) && (shippingMethodKey.length() == 0)) {
			accountEntryShippingOptionRelCacheModel.shippingMethodKey = null;
		}

		accountEntryShippingOptionRelCacheModel.shippingOptionKey =
			getShippingOptionKey();

		String shippingOptionKey =
			accountEntryShippingOptionRelCacheModel.shippingOptionKey;

		if ((shippingOptionKey != null) && (shippingOptionKey.length() == 0)) {
			accountEntryShippingOptionRelCacheModel.shippingOptionKey = null;
		}

		return accountEntryShippingOptionRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AccountEntryShippingOptionRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AccountEntryShippingOptionRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEntryShippingOptionRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AccountEntryShippingOptionRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AccountEntryShippingOptionRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AccountEntryShippingOptionRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEntryShippingOptionRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(AccountEntryShippingOptionRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AccountEntryShippingOptionRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _accountEntryShippingOptionRelId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _accountEntryId;
	private long _channelId;
	private String _shippingMethodKey;
	private String _shippingOptionKey;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AccountEntryShippingOptionRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AccountEntryShippingOptionRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"AccountEntryCSOptionRelId", _accountEntryShippingOptionRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("accountEntryId", _accountEntryId);
		_columnOriginalValues.put("channelId", _channelId);
		_columnOriginalValues.put("shippingMethodKey", _shippingMethodKey);
		_columnOriginalValues.put("shippingOptionKey", _shippingOptionKey);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put(
			"AccountEntryCSOptionRelId", "accountEntryShippingOptionRelId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("AccountEntryCSOptionRelId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("accountEntryId", 128L);

		columnBitmasks.put("channelId", 256L);

		columnBitmasks.put("shippingMethodKey", 512L);

		columnBitmasks.put("shippingOptionKey", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AccountEntryShippingOptionRel _escapedModel;

}