name: Sync Fork
on:
  schedule:
    - cron: '*/60 * * * *' # every 60 minutes
  workflow_dispatch: # on button click
jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Alessio
    steps:
      - name: Preparing environment
        run: |
          echo "Cloning repository..."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          echo "Configuring git..."
          git config --global user.name "alessiorendina"
          git config --global user.email "asilcomando@gmail.com"
          git remote add upstream https://github.com/liferay-commerce/liferay-portal.git
        shell: bash
      - name: Sync Fork
        id: sync-fork
        run: |
          echo "Syncing fork..."
          git fetch upstream
          git checkout master
          lines=$( git diff master..upstream/master -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git pull --rebase upstream master
            git push --force origin master
            echo "Successfully synced!"
          fi
          echo "Fork is updated."
        shell: bash
