name: Sync Fork
on:
  schedule:
    - cron: '*/60 * * * *' # every 60 minutes
  workflow_dispatch: # on button click
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Forks Sync Action
        uses: TobKed/github-forks-sync-action@v0.2.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to clone.
          upstream_repository: liferay/liferay-portal
          # Determines if force push is used
          force: true
